spring:
  datasource:
    url: jdbc:mysql://localhost/taskmanagerdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true